### ISSUE TITLE
Zephyrus S GX531 Support

### ISSUE THREAD

**Issue by DamnWidget** [flukejones/rog-core#18] opened 2020-06-10 12:52 UTC
Hi @flukejones and community

I am currently working on adding support to Zephyrus S GX531 series. This series also features a `1866` device but it doesn't seems to properly work with the current implementation (for example, the ROG and Touchpad Switch doesn't seems to work).

the keyboard also report two codes for the touchpad switch key what is weird, will make a WIP PR later this week. If someone has this model and want to help providing wireshark captures please, don't be shy, I really hate having to install Windows on the machine in order to tackle down that data.

Regards.

P.S: I am not sure how and why I set this up as a bug but looks like I can not remove that label now

**Comment by flukejones** [comment] 2020-06-11 09:06
Glad to see more people finding this and perhaps finding it useful!

**Please provide the following:**
 - Distro:
 - Kernel (`uname -r`):
 - `cat /sys/class/dmi/id/product_name`:
 - `cat /sys/class/dmi/id/product_family`:
 - `cat /sys/class/dmi/id/board_name`:
 - `lsusb |grep 0b05`
   + `sudo lsusb -vd 0b05:<all devices from above> > ~/laptop_info`, and attach to issue.
 - `sudo journalctl -b --unit rog-core > rog-core.log` and attach to issue.
 - `sudo usbhid-dump > usbhid.log` and attach to issue.

I'm intending to create some device documentation at a later date. But this info is always helpful when determining what is different between devices.

**Comment by DamnWidget** [comment] 2020-06-11 14:36
| Field | Description |
| :------ | :-------------- |
|Distribution| Artix GNU/Linux (https://www.artixlinux.org)|
|Kernel| 5.6.14-artix1-1|
|Product Name| Zephyrus S GX531GXR_GX531GXR|
|Product Family | Zephyrus S |
| Motherboard | GX531GXR |
| lsusb | [laptop_info.log](https://github.com/flukejones/rog-core/files/4765473/laptop_info.log) |
| rog-core.log | [rog-core.log](https://github.com/flukejones/rog-core/files/4765438/rog-core.log) |
| usbhid-dump | [usbhid.log](https://github.com/flukejones/rog-core/files/4765426/usbhid.log) |

There you go

**Comment by flukejones** [comment] 2020-06-11 20:35
The issue is Arch. I don't support it but you might have luck with [this](https://github.com/flukejones/rog-core/issues/12#issuecomment-642544306)

**Comment by DamnWidget** [comment] 2020-06-12 15:55
I am not sure to understand what you mean with that but we should probably use another communication via to go further so we do not taint the issues tacker log.

**Comment by aspann** [comment] 2020-06-12 22:02
@flukejones - he uses Atrix .. ;)

@DamnWidget 
Nvm. we're trying to get also that device running, if you're willing to help us with that - you can join our discussion on discord. The invite link can be found in our [README.md](https://lab.retarded.farm/zappel/asus-rog-zephyrus-g14#contribute) 

(we try to maintain a patchset for those devices - and some general knowledge - yes currently official G14 only, but we're willing to extend**)

** we're working together, hand in hand with rog-core from @flukejones .

cheers.

**Comment by aspann** [comment] 2020-06-20 01:18
This issue can be closed, because it's fixed by: https://github.com/flukejones/rog-core/commit/7246acbb663a083da11c67e0804588ed63838ab3

**Closed** 2020-06-22 03:06 UTC
Labels: enhancement
